stages:
    - build


my_build:
    stage: build
    tags: 
      - build
    script:
      - echo 'AAAAAAAAAARRRGH!!!!! 1'
      - cd src/cat
      - make s21_cat
      - cd ../grep
      - make s21_grep
      - echo 'AAAAAAAARRGHHHHHHRRGHH!!!!!!!!!!!!!! 2'
    artifacts:
        paths:
          - src/cat/s21_cat
          - src/grep/s21_grep
        expire_in: 30 days
